image: docker:stable

services:
- docker:dind

Check if library builds in debug and release modes:
  script:
    - docker run -v$(pwd):/source ohboi/minidmd bash -c "
        dub build -b debug &&
        dub build -b release"

Unit-testing and code coverage:
  coverage: '/Average: \d+\.\d+%/'
  script:
    - docker run -v$(pwd):/source -v/root:/root ohboi/minidmd bash -c "
        dub fetch trial     &&
        dub run trial:runner"
    - docker run -v$(pwd):/source -v/root:/root ohboi/minidmd bash -c "
        dub fetch covered               &&
        dub -b unittest-cov -c unittest &&
        dub run covered -- -a"