image: docker:stable

services:
- docker:dind

stages:
  - test
  - coverage

dmd-build: &build
  stage: test
  variables:
    COMPILER: dmd
  script:
    - docker run -v$(pwd):/source ohboi/mini$COMPILER bash -c "dub build -b debug && dub build -b release"

ldc-build:
  <<: *build
  variables:
    COMPILER: ldc

dmd-test: &test
  stage: test
  variables:
    COMPILER: dmd
  script:
    - docker run -v$(pwd):/source ohboi/mini$COMPILER bash -c "dub test"

ldc-test:
  <<: *test
  variables:
    COMPILER: ldc

coverage:
  stage: coverage
  coverage: '/Average: \d+\.\d+%/'
  script:
    - docker run -v$(pwd):/source ohboi/minidmd bash -c "
        dub fetch covered               &&
        dub -b unittest-cov -c unittest &&
        dub run covered -- -a source-tg-d.lst"