image: docker:stable

services:
- docker:dind

dmd: &test
  coverage: '/Average: \d+\.\d+%/'
  variables:
    COMPILER: dmd
  script:
    - docker run -v$(pwd):/source ohboi/mini$COMPILER bash -c "
        dub test &&
        dub fetch covered &&
        dub test -b unittest-cov &&
        dub run covered -- -a source-tg-d.lst"

ldc:
  <<: *test
  variables:
    COMPILER: ldc:beta
