image: docker:stable

services:
- docker:dind

stages:
  - test
  - coverage

dmd: &test
  stage: test
  variables:
    COMPILER: dmd
  script:
    - docker run -v$(pwd):/source ohboi/mini$COMPILER dub test

ldc:
  <<: *test
  variables:
    COMPILER: ldc:beta

coverage:
  stage: coverage
  coverage: '/Average: \d+\.\d+%/'
  script:
    - docker run -v$(pwd):/source ohboi/minidmd bash -c "
        dub fetch covered               &&
        dub -b unittest-cov -c unittest &&
        dub run covered -- -a source-tg-d.lst"