image: docker:stable

services:
- docker:dind

stages:
  - test
  - documentation

dmd:
  stage: test
  coverage: '/Average: \d+\.\d+%/'
  script:
    - docker run -v$(pwd):/source ohboi/minidmd bash -c "
        dub test &&
        dub fetch covered &&
        dub test -b unittest-cov &&
        dub run covered -- -a source-tg-d.lst"

ldc:
  stage: test
  script:
    - docker run -v$(pwd):/source ohboi/minildc:beta dub test

pages:
  stage: documentation
  script:
    - docker run -v$(pwd):/source ohboi/minidmd bash -c "
        apt-get update -qq 2>&1 > /dev/null                     &&
        apt-get install -qq -y --no-install-recommends rsync  &&
        dub build -b ddox && cp -r docs public"
  artifacts:
    paths:
      - public
