image: docker:stable

services:
- docker:dind

dmd:
  coverage: '/Average: \d+\.\d+%/'
  script:
    - docker run -v$(pwd):/source ohboi/minidmd bash -c "
        dub test &&
        dub fetch covered &&
        dub test -b unittest-cov &&
        dub run covered -- -a source-tg-d.lst"

ldc:
  script:
    - docker run -v$(pwd):/source ohboi/minildc:beta dub test
